services:
  web:
    image: django-base:latest
    command: >
      sh -c "python manage.py collectstatic --noinput && uvicorn django_base.asgi:application --host 0.0.0.0 --port 8000"
    working_dir: /app/django_base
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/django_base
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_LANGUAGE_CODE=${DJANGO_LANGUAGE_CODE}
      - DJANGO_TIME_ZONE=${DJANGO_TIME_ZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./django_base/static:/app/django_base/static

  celery:
    image: django-base:latest
    command: celery -A django_base worker --loglevel=info
    volumes:
      - ./django_base:/app/django_base
    working_dir: /app/django_base
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django_base/static:/app/django_base/static:ro
    depends_on:
      - web

  flower:
    image: mher/flower:2.0.1
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery