services:
  # Основной веб-сервис с отладкой ASGI
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/django_base
    volumes:
      - ./django_base:/app/django_base
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m uvicorn django_base.asgi:application --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=django_base.settings_debug
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_LANGUAGE_CODE=${DJANGO_LANGUAGE_CODE}
      - DJANGO_TIME_ZONE=${DJANGO_TIME_ZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy для web сервиса
    depends_on:
      - db
      - rabbitmq
      - redis
    user: "${UID}:${GID}"

  # Celery воркер с отладкой
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/django_base
    volumes:
      - ./django_base:/app/django_base
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 -m celery -A django_base worker --loglevel=info
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - "5679:5679"  # debugpy для celery
    depends_on:
      - db
      - rabbitmq
      - redis
    user: "${UID}:${GID}"

  # База данных PostgreSQL
  db:
    image: postgres:17.5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # RabbitMQ для Celery
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # Redis для WebSocket каналов
  redis:
    image: redis:8
    ports:
      - "6379:6379"

  # Flower для мониторинга Celery
  flower:
    image: mher/flower:2.0.1
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery

  # PgAdmin для управления БД
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
