# Generated by Django 5.2.4 on 2025-10-18 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID сделки')),
                ('trade_date', models.DateTimeField(verbose_name='Дата и время сделки')),
                ('trading_session', models.CharField(choices=[('OPENING', 'Утренняя сессия'), ('LUNCH', 'Обеденная сессия'), ('EVENING', 'Вечерняя сессия'), ('CLOSING', 'Закрытие')], max_length=20, verbose_name='Торговая сессия')),
                ('direction', models.CharField(choices=[('LONG', 'Длинная позиция'), ('SHORT', 'Короткая позиция')], max_length=10, verbose_name='Направление')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена входа')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена выхода')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('leverage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Плечо')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Комиссия')),
                ('planned_stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Плановый стоп-лосс (в пунктах)')),
                ('planned_take_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Плановый тейк-профит (в пунктах)')),
                ('actual_result_points', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Фактический результат (в пунктах)')),
                ('actual_result_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Результат в рублях')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Сделка закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='instruments.instrument', verbose_name='Инструмент')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='strategies.tradingstrategy', verbose_name='Стратегия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Торговая сделка',
                'verbose_name_plural': 'Торговые сделки',
                'db_table': 'trades_trade',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moex_index_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Значение индекса Мосбиржи')),
                ('market_data_json', models.JSONField(blank=True, null=True, verbose_name='Данные рынка (JSON)')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Время сбора данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_context', to='trades.trade', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Контекст рынка',
                'verbose_name_plural': 'Контексты рынка',
                'db_table': 'trades_market_context',
            },
        ),
        migrations.CreateModel(
            name='TradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_reason', models.TextField(verbose_name='Основание для входа')),
                ('exit_reason', models.TextField(blank=True, verbose_name='Основание для закрытия')),
                ('analysis', models.TextField(blank=True, verbose_name='Анализ действий и эмоций')),
                ('conclusions', models.TextField(blank=True, verbose_name='Выводы на будущее')),
                ('emotional_state', models.CharField(blank=True, choices=[('CALM', 'Спокойное'), ('EXCITED', 'Возбужденное'), ('FEARFUL', 'Страх'), ('GREEDY', 'Жадность'), ('CONFIDENT', 'Уверенное')], max_length=20, verbose_name='Эмоциональное состояние')),
                ('tags', models.JSONField(default=list, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания анализа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления анализа')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trades.trade', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Анализ сделки',
                'verbose_name_plural': 'Анализы сделок',
                'db_table': 'trades_trade_analysis',
            },
        ),
        migrations.CreateModel(
            name='TradeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_screenshots/%Y/%m/%d/', verbose_name='Скриншот')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание скриншота')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='trades.trade', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Скриншот сделки',
                'verbose_name_plural': 'Скриншоты сделок',
                'db_table': 'trades_trade_screenshot',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
