# Generated by Django 5.2.4 on 2025-10-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
    ]
