# Generated by Django 5.2.4 on 2025-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_remove_trade_actual_result_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeanalysis',
            name='entry_reason',
        ),
        migrations.RemoveField(
            model_name='tradeanalysis',
            name='exit_reason',
        ),
        migrations.AlterField(
            model_name='trade',
            name='planned_stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Плановый стоп-лосс (цена)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='planned_take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Плановый тейк-профит (цена)'),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='Основание'),
        ),
    ]
