# Generated by Django 5.2.4 on 2025-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_remove_tradeanalysis_entry_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='volume_from_capital',
            field=models.IntegerField(default=10, null=False, blank=False, verbose_name='Объем сделки от капитала'),
        ),
    ]
