# Generated by Django 5.2.4 on 2025-10-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade_volume_from_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('OPEN', 'Открытие позиции'), ('AVERAGE', 'Усреднение'), ('PARTIAL_CLOSE', 'Частичное закрытие'), ('CLOSE', 'Закрытие позиции')], default='OPEN', max_length=15, verbose_name='Тип операции'),
        ),
    ]
