# Generated by Django 5.2.4 on 2025-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=200, verbose_name='Полное название')),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Акция'), ('FUTURES', 'Фьючерс')], max_length=20, verbose_name='Тип инструмента')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Сектор экономики')),
                ('lot_size', models.PositiveIntegerField(default=1, verbose_name='Размер лота')),
                ('min_price_step', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Минимальный шаг цены')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Торговый инструмент',
                'verbose_name_plural': 'Торговые инструменты',
                'db_table': 'instruments_instrument',
                'ordering': ['ticker'],
            },
        ),
    ]
