# Generated by Django 5.2.4 on 2026-03-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Группа индустрии')),
            ],
            options={
                'verbose_name': 'Группа индустрии',
                'verbose_name_plural': 'Группы индустрий',
                'db_table': 'instruments_industry_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='logolink',
            field=models.CharField(blank=True, default='instruments/ticker_icons/blank_ticker.svg', max_length=500, verbose_name='Ссылка на логотип (малая иконка)'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='og_logo',
            field=models.CharField(blank=True, default='instruments/ticker_icons/blank_ticker.svg', max_length=500, verbose_name='Ссылка на большую иконку (og_logo)'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('STOCK', 'Акция'), ('INDEX', 'Индекс'), ('BOND', 'Облигация'), ('ETF', 'Биржевой фонд'), ('CURRENCY', 'Валюта')], max_length=20, verbose_name='Тип инструмента'),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Индустрия')),
                ('industry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='instruments.industrygroup', verbose_name='Группа индустрии')),
            ],
            options={
                'verbose_name': 'Индустрия',
                'verbose_name_plural': 'Индустрии',
                'db_table': 'instruments_industry',
                'ordering': ['name'],
                'unique_together': {('name', 'industry_group')},
            },
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подгруппа индустрии')),
                ('description', models.TextField(blank=True, verbose_name='Описание подгруппы индустрии')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='instruments.industry', verbose_name='Индустрия')),
            ],
            options={
                'verbose_name': 'Подгруппа индустрии',
                'verbose_name_plural': 'Подгруппы индустрий',
                'db_table': 'instruments_sub_industry',
                'ordering': ['name'],
                'unique_together': {('name', 'industry')},
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='sub_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.subindustry', verbose_name='Подгруппа индустрии'),
        ),
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, verbose_name='Тикер контракта')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название контракта')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата экспирации')),
                ('min_price_step', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Минимальный шаг цены (если отличается от базового актива)')),
                ('lot_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер лота (если отличается)')),
                ('currency', models.CharField(blank=True, default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures', to='instruments.instrument', verbose_name='Базовый актив')),
            ],
            options={
                'verbose_name': 'Фьючерс',
                'verbose_name_plural': 'Фьючерсы',
                'db_table': 'instruments_futures',
                'ordering': ['base_asset', 'expiration_date'],
                'unique_together': {('base_asset', 'ticker')},
            },
        ),
    ]
