# Generated by Django 5.2.4 on 2026-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_normalize_sector_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futures',
            name='min_price_step',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Минимальный шаг цены (если отличается от базового актива)'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='min_price_step',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Минимальный шаг цены'),
        ),
    ]
