# Generated by Django 5.2.4 on 2026-03-28 15:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_widen_min_price_step_precision'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('ticker', config='simple'), '||', django.contrib.postgres.search.SearchVector('name', 'description', 'sector', config='russian'), django.contrib.postgres.search.SearchConfig('simple')), name='instruments_instr_fts_gin'),
        ),
    ]
