# Generated by Django 5.2.4 on 2026-03-31 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_instrument_fts_gin_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesAssetCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(help_text='Значение поля ASSETCODE в ответе ISS для FORTS, например SBRF для контрактов на Сбер.', max_length=75, unique=True, verbose_name='ASSETCODE фьючерса (Мосбиржа)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Учитывать при загрузке')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('base_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='futures_asset_code_mappings', to='instruments.instrument', verbose_name='Базовый актив')),
            ],
            options={
                'verbose_name': 'Сопоставление фьючерса с базовым активом',
                'verbose_name_plural': 'Сопоставления фьючерсов с базовыми активами',
                'db_table': 'instruments_futures_asset_code_mapping',
                'ordering': ['asset_code'],
            },
        ),
    ]
