# Generated by Django 5.2.4 on 2026-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_futures_asset_code_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='futures',
            name='secid',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='SECID на MOEX (для API-запросов)'),
        ),
    ]
