# Generated by Django 5.2.4 on 2026-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_add_futures_secid'),
    ]

    operations = [
        migrations.AddField(
            model_name='futures',
            name='tinkoff_uid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='T-Invest UID'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tinkoff_uid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='T-Invest UID'),
        ),
    ]
