# Generated by Django 5.2.4 on 2025-10-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название стратегии')),
                ('description', models.TextField(blank=True, verbose_name='Описание стратегии')),
                ('strategy_type', models.CharField(choices=[('SCALPING', 'Скальпинг'), ('DAY_TRADING', 'Дневная торговля'), ('SWING', 'Свинг-торговля'), ('POSITION', 'Позиционная торговля')], max_length=20, verbose_name='Тип стратегии')),
                ('instruments', models.CharField(choices=[('STOCKS', 'Акции'), ('FUTURES', 'Фьючерсы'), ('BOTH', 'Акции и фьючерсы')], default='BOTH', max_length=20, verbose_name='Типы инструментов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_strategies', to=settings.AUTH_USER_MODEL, verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Торговая стратегия',
                'verbose_name_plural': 'Торговые стратегии',
                'db_table': 'strategies_trading_strategy',
                'ordering': ['-created_at'],
            },
        ),
    ]
