# Generated by Django 5.2.4 on 2025-10-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Начальный депозит (руб.)')),
                ('current_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Текущий депозит (руб.)')),
                ('use_default_deposit', models.BooleanField(default=False, verbose_name='Использовать дефолтный депозит (1 млн руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль трейдера',
                'verbose_name_plural': 'Профили трейдеров',
                'db_table': 'accounts_trader_profile',
            },
        ),
    ]
