# Generated by Django 5.2.4 on 2025-10-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderprofile',
            name='current_deposit',
        ),
        migrations.RemoveField(
            model_name='traderprofile',
            name='initial_deposit',
        ),
        migrations.RemoveField(
            model_name='traderprofile',
            name='use_default_deposit',
        ),
    ]
