# Generated by Django 5.2.4 on 2026-05-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_traderprofile_current_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='_tinkoff_token',
            field=models.TextField(blank=True, db_column='tinkoff_token', default='', verbose_name='T-Invest API токен (зашифрованный)'),
        ),
    ]
